name: Compile Pico UF2

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Toolchain
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential python3

    - name: Clone Pico SDK
      run: |
        git clone -b master https://github.com/raspberrypi/pico-sdk.git
        echo "PICO_SDK_PATH=$PWD/pico-sdk" >> $GITHUB_ENV

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DPICO_SDK_PATH=${{ env.PICO_SDK_PATH }} ..
        make -j4

    - name: Upload UF2
      uses: actions/upload-artifact@v3
      with:
        name: firmware-uf2
        path: build/*.uf2
